title: My awesome website
author: Jeffrey Han
email: jshan@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  APCSP, learning GitHub after AP test.

# social links
twitter_username: jshaaaaan # DO NOT include the @ character, or else the build will fail!
github_username:  eggcustap # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
